#!/usr/bin/env python3

import getpass
import os
import pwd
import sys

import i3ipc


MARK = 'sway-quake'
TITLE = '__sway_quake__'

OPTIONS = (
    'floating enable,'
    'sticky enable,'
    'border none,'
    'resize set width 100ppt height 30ppt,'
    'move absolute position 0px 0px,'
    'opacity 0.95'
)

def exec_command(args):
    os.execvp(args[0], args)


def quake_start_terminal():
    exec_command([
        'gnome-terminal',
        '-t',
        TITLE,
        '--',
        'sway-quake',
        'spawn',
    ])

def quake_toggle():
    ipc = i3ipc.Connection()
    tree = ipc.get_tree()
    windows = tree.find_marked(MARK)
    if not windows:
        quake_start_terminal()
    else:
        if windows[0].ipc_data['visible']:
            ipc.command(f'[con_mark="{MARK}"] move scratchpad')
        else:
            ipc.command(
                f'[con_mark="{MARK}"] scratchpad show, {OPTIONS}'
            )

def quake_spawn():
    ipc = i3ipc.Connection()
    ipc.command(f'[title="{TITLE}"] mark {MARK}')
    ipc.command(f'[con_mark="{MARK}"] scratchpad show, {OPTIONS}')
    shell = pwd.getpwnam(getpass.getuser()).pw_shell
    exec_command([shell])


def main():
    if sys.argv[1] == 'toggle':
        quake_toggle()
    elif sys.argv[1] == 'spawn':
        quake_spawn()
    else:
        raise RuntimeError(f'Unknown command {sys.argv[1]}')


if __name__ == '__main__':
    main()
