#!/bin/sh

# Initialize environment
systemctl --user import-environment             \
          SWAYSOCK                              \
          DISPLAY                               \
          I3SOCK                                \
          WAYLAND_DISPLAY                       \
          XCURSOR_SIZE                          \
          XCURSOR_THEME

# Notify systemd that sway is ready
if [ -z "$NOTIFY_SOCKET" ]; then
    echo "No notify socket available, nothing to do"
    exit 0
fi

echo "Going to notify systemd"
exec systemd-notify --ready
