#!/bin/sh

if swaymsg -t get_tree |
        jq -e \
           '.. | select(.type? and .focused==true) |
                 select((.app_id // .window_properties.class? // "") |
                     test("^emacs.*";"i"))' > /dev/null; then
    exec swaymsg 'input "*" xkb_switch_layout 0'
else
    exec swaymsg 'input "*" xkb_switch_layout next'
fi
