#!/bin/sh

ZOOM=$(xdotool search --limit 1 --name "Zoom Meeting")
CURRENT=$(xdotool getwindowfocus)

if [ "x$ZOOM" = "" ]; then
   echo "No zoom meeting window found"
   exit 1
fi

xdotool windowactivate --sync ${ZOOM}
xdotool key --clearmodifiers --window $ZOOM "alt+a"
xdotool windowactivate --sync ${CURRENT}

