" no compatibility with vi
set nocompatible

syntax on

if has("gui_running")
	colors desert
	" line numbers color
	hi LineNr guifg=grey45 guibg=grey20
endif

" enable filetype plugins and indents
filetype on
filetype plugin on
filetype indent on

set ttyfast

set tabstop=4 shiftwidth=4 softtabstop=4 autoindent smartindent

" prefer unix over windows over mac formats
set ffs=unix,dos,mac

" show tabs and trailing spaces
set listchars=tab:··,trail:·
set list

" utf-8 default encoding
set enc=utf-8

" show line numbers
"set number

" read file again, if it was changed outside of vim
set autoread

