#!/usr/bin/env python3
import sys
import pathlib

from ruamel.yaml import YAML

yaml = YAML()

YAML_SEARCH_PATHES = (
    pathlib.Path('~/arcadia/taxi/schemas/schemas/services/'),
)

def yaml_ref_find(doc, ref):
    for path in ref[1:].split('/'):
        if not path:
            continue
        try:
            doc = doc[path]
        except KeyError:
            return None
    return doc


def yaml_find_file(ref_path, current_path):
    if ref_path[:1] in ('.', '/'):
        return pathlib.Path(current_path.parent / ref_path)

    for base in YAML_SEARCH_PATHES:
        base = base.expanduser()
        path = base / ref_path
        if path.exists():
            return path
    return None


def yaml_path_find(filename, doc, ref):
    if ref[:1] == '#':
        return filename, yaml_ref_find(doc, ref[1:])
    ref_path, ref = ref.split('#', 1)

    ref_filename = yaml_find_file(ref_path, filename)
    if not ref_filename:
        return filename, None
    with ref_filename.open() as fp:
        doc = yaml.load(fp.read())
    return ref_filename, yaml_ref_find(doc, ref)


def main():
    filename = pathlib.Path(sys.argv[1])
    symbol = sys.argv[2]

    with filename.open() as fp:
        doc = yaml.load(fp.read())

    filename, node = yaml_path_find(filename, doc, symbol)
    if node:
        print(filename, node.lc.line + 1, node.lc.col, "yaml node", sep='\t')



if __name__ == '__main__':
    main()
