#!/bin/sh

# SCHROOT_SESSION_DIR=$HOME/.config/schroot
# SCHROOT_SESSION_PATH=$SCHROOT_SESSION_DIR/.bionic

# schroot --begin-session -c bionic -n bionic
# schroot --exclude-aliases  --end-session -c bionic

SCHROOT_SESSION_ID="$(basename $0)"
SCHROOT_DIR="/run/schroot/mount/$SCHROOT_SESSION_ID"
SCHROOT_SESSION_FILE="/var/lib/schroot/session/$SCHROOT_SESSION_ID"

if [ "$SCHROOT_CHROOT_NAME" = "$SCHROOT_SESSION_ID" ]; then
    exec "$@"
fi

if [ -n "$SCHROOT_CHROOT_NAME" ]; then
    exec >&2
    echo "Already running other schroot session: $SCHROOT_CHROOT_NAME"
    exit 1
fi

if [ ! -d "$SCHROOT_DIR" ]; then
    if [ -f "$SCHROOT_SESSION_FILE" ]; then
        schroot-session-end "$SCHROOT_SESSION_ID"
    fi
    schroot --begin-session -c "${SCHROOT_SESSION_ID}" -n "${SCHROOT_SESSION_ID}"
fi

exec schroot -r -c "$SCHROOT_SESSION_ID" -- "$@"
